long block process test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -281,6 +281,31 @@ jobs:
                 # if mix failed, then coveralls_report won't run, so signal done here and return original exit status
                 (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && exit $retval)
             fi
+  
+  watcher_info_coveralls_and_integration_tests:
+    executor: builder_pg_geth
+    environment:
+      MIX_ENV: test
+    steps:
+      - setup_elixir-omg_workspace
+      - restore_cache:
+          keys:
+            - v2-mix-cache-test-compile-{{ checksum "mix.lock" }}-{{ .Branch }}-{{ .Revision }}
+      - run:
+          name: Compile
+          command: mix compile
+      - run:
+          name: Integration Tests & Coveralls Part Watcher
+          command: |
+            # Don't submit coverage report for forks, but let the build succeed
+            export SHELL=/bin/bash
+            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
+              mix coveralls.html --parallel --umbrella --include watcher_info --exclude watcher --exclude child_chain --exclude common --exclude test --trace
+            else
+              mix coveralls.circle --parallel --umbrella --include watcher_info --exclude watche --exclude child_chain --exclude common --exclude test --trace ||
+                # if mix failed, then coveralls_report won't run, so signal done here and return original exit status
+                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && exit $retval)
+            fi
 
   common_coveralls_and_integration_tests:
     executor: builder_pg_geth
@@ -745,13 +770,16 @@ workflows:
           requires:
             - child_chain_coveralls_and_integration_tests
             - watcher_coveralls_and_integration_tests
-
+            - watcher_info_coveralls_and_integration_tests
             - common_coveralls_and_integration_tests
             - test
       - child_chain_coveralls_and_integration_tests:
           requires: [build]
           filters: *all_branches_and_tags
       - watcher_coveralls_and_integration_tests:
+          requires: [build]
+          filters: *all_branches_and_tags
+      - watcher_info_coveralls_and_integration_tests:
           requires: [build]
           filters: *all_branches_and_tags
       - common_coveralls_and_integration_tests:
@@ -787,6 +815,7 @@ workflows:
             [
               child_chain_coveralls_and_integration_tests,
               watcher_coveralls_and_integration_tests,
+              watcher_info_coveralls_and_integration_tests
               common_coveralls_and_integration_tests,
               test,
               property_tests,
@@ -809,6 +838,7 @@ workflows:
             [
               child_chain_coveralls_and_integration_tests,
               watcher_coveralls_and_integration_tests,
+              watcher_info_coveralls_and_integration_tests
               common_coveralls_and_integration_tests,
               test,
               property_tests,
@@ -823,6 +853,7 @@ workflows:
             [
               child_chain_coveralls_and_integration_tests,
               watcher_coveralls_and_integration_tests,
+              watcher_info_coveralls_and_integration_tests
               common_coveralls_and_integration_tests,
               test,
               property_tests,
