feat: update Makefile and circleci configs for watcher_informational and pray that it works

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,8 +60,7 @@ executors:
   metal_watcher_informational:
     machine: true
     environment:
-      # Informational watcher reuses the watcher image, which is the full image, for now.
-      WATCHER_INFORMATIONAL_IMAGE_NAME: "omisego/watcher"
+      WATCHER_INFORMATIONAL_IMAGE_NAME: "omisego/watcher_informational"
 
 commands:
   setup_elixir-omg_workspace:
@@ -238,9 +237,34 @@ jobs:
             # Don't submit coverage report for forks, but let the build succeed
             export SHELL=/bin/bash
             if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
-              mix coveralls.html --parallel --umbrella --include watcher --include watcher_informational --exclude child_chain --exclude common --exclude test --trace
+              mix coveralls.html --parallel --umbrella --include watcher --exclude watcher_informational --exclude child_chain --exclude common --exclude test --trace
             else
-              mix coveralls.circle --parallel --umbrella --include watcher --include watcher_informational --exclude child_chain --exclude common --exclude test --trace ||
+              mix coveralls.circle --parallel --umbrella --include watcher --exclude watcher_informational --exclude child_chain --exclude common --exclude test --trace ||
+                # if mix failed, then coveralls_merge won't run, so signal done here and return original exit status
+                (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && exit $retval)
+            fi
+
+  watcher_informational_coveralls_and_integration_tests:
+    executor: builder_pg_geth
+    environment:
+      MIX_ENV: test
+    steps:
+      - setup_elixir-omg_workspace
+      - restore_cache:
+          keys:
+            - v2-mix-cache-test-compile-{{ checksum "mix.lock" }}-{{ .Branch }}-{{ .Revision }}
+      - run:
+          name: Compile
+          command: mix compile
+      - run:
+          name: Integration Tests & Coveralls Part Watcher Informational
+          command: |
+            # Don't submit coverage report for forks, but let the build succeed
+            export SHELL=/bin/bash
+            if [[ -z "$COVERALLS_REPO_TOKEN" ]]; then
+              mix coveralls.html --parallel --umbrella --include watcher_informational --exclude watcher --exclude child_chain --exclude common --exclude test --trace
+            else
+              mix coveralls.circle --parallel --umbrella --include watcher_informational --exclude watcher --exclude child_chain --exclude common --exclude test --trace ||
                 # if mix failed, then coveralls_merge won't run, so signal done here and return original exit status
                 (retval=$? && curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done" && exit $retval)
             fi
@@ -359,7 +383,7 @@ jobs:
       - checkout
       - run: make docker-child_chain CHILD_CHAIN_IMAGE_NAME="omisego/child_chain"
       - run: make docker-watcher WATCHER_IMAGE_NAME="omisego/watcher"
-      - run: make docker-watcher_informational WATCHER_INFORMATIONAL_IMAGE_NAME="omisego/watcher"
+      - run: make docker-watcher_informational WATCHER_INFORMATIONAL_IMAGE_NAME="omisego/watcher_informational"
       - run: docker-compose -f docker-compose.yml -f priv/docker-compose.geth-ganache.yml pull
       - run: docker-compose -f docker-compose.yml -f priv/docker-compose.geth-ganache.yml up -d
       - run:
@@ -473,8 +497,12 @@ jobs:
       - run: make docker-watcher WATCHER_IMAGE_NAME=$WATCHER_IMAGE_NAME
       - run: IMAGE_NAME=$WATCHER_IMAGE_NAME sh .circleci/ci_publish.sh
 
-  # Note: `publish_watcher_informational` job is not available because the informational watcher
-  # is published with the watcher docker image at least for now (26-Nov-19).
+  publish_watcher_informational:
+    executor: metal_watcher
+    steps:
+      - checkout
+      - run: make docker-watcher_informational WATCHER_INFORMATIONAL_IMAGE_NAME=$WATCHER_IMAGE_NAME
+      - run: IMAGE_NAME=$WATCHER_INFORMATIONAL_IMAGE_NAME sh .circleci/ci_publish.sh
 
   deploy_child_chain:
     executor: deploy
@@ -583,7 +611,7 @@ jobs:
             kubectl set image statefulset childchain childchain=$DOCKER_IMAGE
             while true; do if [ "$(kubectl get pods childchain-0 -o jsonpath=\"{.status.phase}\" | grep Running)" ]; then break; fi; done
             kubectl set image statefulset watcher watcher=$DOCKER_IMAGE
-            kubectl set image statefulset watcher_informational watcher=$DOCKER_IMAGE
+            kubectl set image statefulset watcher_informational watcher_informational=$DOCKER_IMAGE
 
 workflows:
   version: 2
@@ -616,11 +644,14 @@ workflows:
           requires:
             - child_chain_coveralls_and_integration_tests
             - watcher_coveralls_and_integration_tests
+            - watcher_informational_coveralls_and_integration_tests
             - common_coveralls_and_integration_tests
             - test
       - child_chain_coveralls_and_integration_tests:
           requires: [build]
       - watcher_coveralls_and_integration_tests:
+          requires: [build]
+      - watcher_informational_coveralls_and_integration_tests:
           requires: [build]
       - common_coveralls_and_integration_tests:
           requires: [build]
@@ -645,6 +676,7 @@ workflows:
             - test
             - child_chain_coveralls_and_integration_tests
             - watcher_coveralls_and_integration_tests
+            - watcher_informational_coveralls_and_integration_tests
             - common_coveralls_and_integration_tests
           filters:
             branches:
@@ -656,6 +688,7 @@ workflows:
             [
               child_chain_coveralls_and_integration_tests,
               watcher_coveralls_and_integration_tests,
+              watcher_informational_coveralls_and_integration_tests,
               common_coveralls_and_integration_tests,
               test,
               dialyzer,
@@ -670,6 +703,7 @@ workflows:
             [
               child_chain_coveralls_and_integration_tests,
               watcher_coveralls_and_integration_tests,
+              watcher_informational_coveralls_and_integration_tests,
               common_coveralls_and_integration_tests,
               test,
               dialyzer,
@@ -679,25 +713,36 @@ workflows:
             branches:
               only:
                 - master
-
-      # Note: `publish_watcher_informational` job is not part of the build-deploy workflow here
-      # because the informational watcher is the same docker image as the watcher (26-Nov-19).
-
+      - publish_watcher_informational:
+          requires:
+            [
+              child_chain_coveralls_and_integration_tests,
+              watcher_coveralls_and_integration_tests,
+              watcher_informational_coveralls_and_integration_tests,
+              common_coveralls_and_integration_tests,
+              test,
+              dialyzer,
+              lint,
+            ]
+          filters:
+            branches:
+              only:
+                - master
       # Release deploy to development in case of master branch.
       - deploy_child_chain:
-          requires: [publish_child_chain, publish_watcher]
+          requires: [publish_child_chain, publish_watcher, publish_watcher_informational]
           filters:
             branches:
               only:
                 - master
       - deploy_watcher:
-          requires: [publish_child_chain, publish_watcher]
+          requires: [publish_child_chain, publish_watcher, publish_watcher_informational]
           filters:
             branches:
               only:
                 - master
       - deploy_watcher_informational:
-          requires: [publish_child_chain, publish_watcher]
+          requires: [publish_child_chain, publish_watcher, publish_watcher_informational]
           filters:
             branches:
               only:
