feat: fail the github action instead of relying on a bot

diff --git a/.github/workflows/enforce-changelog-labels.yml b/.github/workflows/enforce-changelog-labels.yml
--- a/.github/workflows/enforce-changelog-labels.yml
+++ b/.github/workflows/enforce-changelog-labels.yml
@@ -9,8 +9,6 @@ jobs:
   enforce-changelog-label:
     runs-on: ubuntu-latest
     env:
-      APPROVAL_MESSAGE: "The PR has a valid changelog label."
-      REJECTION_MESSAGE: "The PR is missing a valid changelog label."
       # When updating the labels here, also update the `configure-sections` of the `.github_changelog_generator` file
       ONE_OF_LABELS: "api|enhancement|breaking|bug|chore|documentation"
     steps:
@@ -25,20 +23,13 @@ jobs:
           | cut -d'"' -f4 \
           | grep -E $ONE_OF_LABELS
 
-      - name: Approve the PR if a changelog label is found
-        if: steps.check-changelog-label.outcome == 'success'
+      - name: Print success message
+        if: ${{ success() }}
         run: |
-          echo $APPROVAL_MESSAGE
-          curl -X POST "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/reviews" \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: token ${{ secrets.HOUSE_KEEPER_BOT_TOKEN }}" \
-            --data "{\"event\": \"APPROVE\", \"body\": \"${APPROVAL_MESSAGE}\"}"
+          echo "The PR has a valid changelog label."
 
-      - name: Request change on the PR if a changelog label is missing
-        if: steps.check-changelog-label.outcome == 'failure'
+      - name: Print failure message
+        if: ${{ failure() }}
         run: |
-          echo $REJECTION_MESSAGE
-          curl -X POST "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/reviews" \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: token ${{ secrets.HOUSE_KEEPER_BOT_TOKEN }}" \
-            --data "{\"event\": \"REQUEST_CHANGES\", \"body\": \"${REJECTION_MESSAGE} Label the PR with one of: ${ONE_OF_LABELS//|/, }.\"}"
+          echo "The PR is missing a valid changelog label. Label the PR with one of: ${ONE_OF_LABELS//|/, }."
+          exit 1
